// AlIPS — the syllabus topic list, shared by the lesson planner and the
// worksheet generator so both offer exactly the same topics.
//
// The topic list is the department's Annual Syllabus (data.js), not the list of
// question generators. Where a syllabus sub-topic also has a generator, the
// tools can produce questions for it; where it does not, the planner still
// drafts a lesson and the worksheet generator marks it as unavailable.

// ---------- Curriculum topics → question generators ----------
// The topic list comes from the annual syllabus (data.js), so every topic the
// department teaches can be planned. Where a topic also has a question
// generator, the plan gets starter, practice and homework questions too;
// where it does not, the plan is still drafted, just without them.

const STOPWORDS = new Set(["a", "an", "the", "of", "and", "or", "to", "in", "on",
  "for", "with", "by", "from", "as", "is", "are", "its", "their", "using", "use"]);

// Lowercase, strip punctuation, drop filler words, and take a crude stem so
// "circle" matches "circles" and "equation" matches "equations".
const words = (s) => String(s).toLowerCase()
  .replace(/[^a-z0-9 ]+/g, " ")
  .split(/\s+/)
  .filter((w) => w && !STOPWORDS.has(w))
  .map((w) => w.replace(/(ies)$/, "y").replace(/(es|s)$/, ""));

// Curriculum wording that no amount of word matching will connect to the
// generator that actually covers it. Primary needs most of these: the annual
// plan says "Finding totals" and "Taking away" where the generators say
// "Addition within 20" and "Subtraction within 20". Add to this table as
// more generators are written.
const TOPIC_ALIASES = {
  // Stage 1-2 number
  "adding numbers by counting on": "addWithin20",
  "counting on for addition": "addWithin20",
  "finding totals": "addWithin20",
  "addition facts to 5": "addWithin20",
  "pairs that total 10": "addWithin20",
  "pairs that total 20": "addWithin20",
  "equivalent addition facts": "addWithin20",
  "adding small numbers": "addWithin20",
  "combining sets of objects to add to 20": "addWithin20",
  "adding amounts up to 20": "addWithin20",
  "addition and subtraction facts for 10": "addWithin20",
  "addition and subtraction facts for 20": "addWithin20",
  "addition and subtraction with numbers to 20": "addWithin20",
  "subtracting numbers by counting back": "subWithin20",
  "counting back for subtraction": "subWithin20",
  "taking away": "subWithin20",
  "taking away a small number of objects": "subWithin20",
  "finding the difference": "subWithin20",
  "subtracting amounts up to 20": "subWithin20",
  "subtracting on a number line": "subWithin20",
  "counting up on a number line to find the difference": "subWithin20",
  "tens and ones making numbers": "placeValue",
  "tens and ones breaking up numbers": "placeValue",
  "tens and ones": "placeValue",
  // Stage 2-3 multiplication and division
  "counting in twos fives and tens": "timesTables",
  "multiplication as repeated addition": "timesTables",
  "multiplication tables of 1 and 2": "timesTables",
  "multiplication tables of 5 and 10": "timesTables",
  "multiplication tables of 2 4 and 8": "timesTables",
  "multiplication tables of 3 6 and 9": "timesTables",
  "learning multiplication tables": "timesTables",
  "multiples of 2 5 and 10": "timesTables",
  "division as sharing": "divisionRemainder",
  "division as grouping": "divisionRemainder",
  "division with and without remainders": "divisionRemainder",
  "sharing for division": "divisionRemainder",
  "grouping for division": "divisionRemainder",
  "adding pairs of two digit numbers": "columnAdd",
  "adding pairs of 2 digit numbers": "columnAdd",
  "adding pairs of 3 digit numbers": "columnAdd",
  "adding two digit and one digit numbers": "columnAdd",
  "adding pairs of 2 digit and 3 digit numbers": "columnAdd",
  "subtracting two digit numbers": "columnSub",
  "subtracting 2 digit numbers": "columnSub",
  "subtracting with 3 digit numbers": "columnSub",
  "subtracting 2 digit numbers from 3 digit numbers": "columnSub",
  "subtracting a one digit number from a two digit number": "columnSub",
  "fractions of a group": "fractionOfAmount",
  "divide to find fractions": "fractionOfAmount",
  "fractions of shapes and quantities": "fractionOfAmount",
  "fractions as operators": "fractionOfAmount",
  "percentage of shapes and quantities": "percentOfAmount",
  "percentages": "percentOfAmount",
  "introducing percentages": "percentOfAmount",
  "multiplying larger numbers": "longMultiplication",
  "multiplying 2 digit numbers": "longMultiplication",
  "multiplying a 2 digit number by a 1 digit number": "longMultiplication",
  "multiplying a 3 digit number by a 1 digit number": "longMultiplication",
  "multiplying by a 2 digit number": "longMultiplication",
  "multiplying numbers up to 1000": "longMultiplication",
  "multiplying whole numbers up to 10 000": "longMultiplication",
  "calculating angles in triangles": "anglesTriangle",
  "perimeter and area": "areaPerimeterRect",
  // --- Added with the 2026-27 generator batch: the department's own wording ---
  "tracing numbers 1 to 10": "readWriteNumbers",
  "reading and writing numbers": "readWriteNumbers",
  "reading and writing numbers to 20": "readWriteNumbers",
  "reading and writing numbers to 100": "readWriteNumbers",
  "recognising numbers": "readWriteNumbers",
  "counting objects": "readWriteNumbers",
  "how many": "readWriteNumbers",
  "number worksheets": "readWriteNumbers",
  "understanding numbers to 20": "readWriteNumbers",
  "estimating and counting to 100": "compareNumbers",
  "counting to 1000": "countingSequence",
  "counting on and counting back": "countingSequence",
  "counting on and back": "countingSequence",
  "counting in tens and ones": "countingSequence",
  "counting in fives": "countingSequence",
  "counting in twos": "countingSequence",
  "number patterns": "countingSequence",
  "patterns and sequences": "countingSequence",
  "working with sequences": "countingSequence",
  "identifying and building sequences": "countingSequence",
  "linear sequences": "countingSequence",
  "sequences": "countingSequence",
  "more about sequences": "countingSequence",
  "larger and smaller numbers": "compareNumbers",
  "comparing numbers": "compareNumbers",
  "comparing and ordering numbers": "compareNumbers",
  "comparing and ordering 3 digit numbers": "compareNumbers",
  "comparing and ordering decimal numbers": "compareNumbers",
  "comparing and ordering quantities": "compareNumbers",
  "larger numbers": "placeValueParts",
  "one more and one less": "oneMoreLess",
  "counting on 10 counting back 10": "oneMoreLess",
  "even numbers and odd numbers": "oddEven",
  "even and odd numbers": "oddEven",
  "first second third": "ordinals",
  "pattern and ordinals": "ordinals",
  "doubling numbers up to 10": "doubleHalve",
  "halving numbers": "doubleHalve",
  "multiplication as doubling": "doubleHalve",
  "rounding numbers": "rounding",
  "rounding to the nearest 10": "rounding",
  "rounding to the nearest 100": "rounding",
  "rounding to the nearest 10 or 100": "rounding",
  "rounding to the nearest whole number": "rounding",
  "rounding decimal numbers": "rounding",
  "making estimates": "rounding",
  "using rounding to help with adding and subtracting": "rounding",
  "adding multiples of 10": "multiplesOf10",
  "adding multiples of 100": "multiplesOf10",
  "adding multiples of 10 and 100": "multiplesOf10",
  "adding and subtracting multiples of 10": "multiplesOf10",
  "complements to 100": "complementsTo100",
  "addition and subtraction facts to 100": "complementsTo100",
  "hundreds tens and ones": "placeValueParts",
  "composing decomposing and regrouping": "placeValueParts",
  "number and place value": "placeValueParts",
  "more about numbers and place value": "placeValueParts",
  "multiplying by 10": "multiplyBy10",
  "multiplying and dividing whole numbers by 10 and 100": "multiplyBy10",
  "multiplying and dividing whole numbers by 10 100 and 1000": "multiplyBy10",
  "the relationship between factors and multiples": "factorsMultiples",
  "factors and multiples": "factorsMultiples",
  "common multiples and common factors": "factorsMultiples",
  "finding common multiples and common factors": "factorsMultiples",
  "square numbers": "squareCubeNumbers",
  "cube numbers": "squareCubeNumbers",
  "triangular numbers": "squareCubeNumbers",
  "prime numbers": "primeNumbers",
  "tests of divisibility": "divisibility",
  "using tests of divisibility": "divisibility",
  "divisibility": "divisibility",
  "the relationship between addition and subtraction": "missingOperation",
  "the relationship between multiplication and division": "missingOperation",
  "using multiplication and division facts": "missingOperation",
  "multiplication and division facts": "missingOperation",
  "calculation with missing numbers": "missingOperation",
  "finding the value of missing numbers": "missingOperation",
  "missing number problems": "missingOperation",
  "more missing number problems": "missingOperation",
  "skills for calculating": "missingOperation",
  "using arrays to show multiplication": "arraysMultiplication",
  "division as repeated subtraction": "arraysMultiplication",
  "multiplying numbers": "arraysMultiplication",
  "money": "moneyTotals",
  "understanding coins and notes": "moneyTotals",
  "working out the total amount": "moneyTotals",
  "making amounts": "moneyTotals",
  "working with money": "moneyTotals",
  "calculating with money": "moneyTotals",
  "money and finance": "moneyTotals",
  "fractions and equal parts": "fractionOfShape",
  "finding half of a shape": "fractionOfShape",
  "equal parts": "fractionOfShape",
  "equal parts of a whole": "fractionOfShape",
  "understanding half and whole": "fractionOfShape",
  "parts and wholes": "fractionOfShape",
  "three quarters": "fractionOfShape",
  "one quarter two quarters three quarters": "fractionOfShape",
  "equal sharing": "equalSharing",
  "equal shares": "equalSharing",
  "comparing and ordering fractions": "compareFractions",
  "improper fractions and mixed numbers": "improperMixed",
  "mixed numbers and improper fractions": "improperMixed",
  "mixed numbers": "improperMixed",
  "introducing decimal numbers": "decimalPlaceValue",
  "decimal numbers": "decimalPlaceValue",
  "decimal places": "decimalPlaceValue",
  "adding and subtracting decimal numbers": "addDecimals",
  "multiplying decimal numbers": "multiplyDecimals",
  "multiplying and dividing decimal numbers": "multiplyDecimals",
  "fraction decimal and percentage equivalences": "fdpEquivalence",
  "equivalent fractions decimals and percentages": "fdpEquivalence",
  "fractions and division": "multiplyFraction",
  "multiplying and dividing proper fractions by whole numbers": "multiplyFraction",
  "multiplying and dividing unit fractions by a whole number": "multiplyFraction",
  "multiplication and division of fractions": "multiplyFraction",
  "3d shapes": "shapeProperties",
  "2d and 3d shapes": "shapeProperties",
  "2d and 3d shape names": "shapeProperties",
  "shapes around us": "shapeProperties",
  "2d shapes and their properties": "shapeProperties",
  "3d shapes and their properties": "shapeProperties",
  "naming and sorting shapes": "shapeProperties",
  "sorting shapes": "shapeProperties",
  "polygons": "shapeProperties",
  "regular and irregular polygons": "shapeProperties",
  "properties of quadrilaterals": "shapeProperties",
  "hierarchy of quadrilaterals": "shapeProperties",
  "squares and rectangles": "shapeProperties",
  "triangles": "shapeProperties",
  "three dimensional shapes": "shapeProperties",
  "symmetry": "symmetryLines",
  "symmetrical shapes": "symmetryLines",
  "symmetrical patterns": "symmetryLines",
  "rotational symmetry": "symmetryLines",
  "reflective and rotational symmetry": "symmetryLines",
  "time": "tellTime",
  "measuring time": "tellTime",
  "12 and 24 hour clock": "tellTime",
  "calculating time intervals": "timeIntervals",
  "duration": "timeIntervals",
  "calculating start and end times": "timeIntervals",
  "days weeks months and years": "timeIntervals",
  "calendars and timetables": "timeIntervals",
  "length": "unitConversion",
  "mass": "unitConversion",
  "capacity": "unitConversion",
  "measures": "unitConversion",
  "measuring": "unitConversion",
  "the metric system and converting units": "unitConversion",
  "large and small units": "unitConversion",
  "perimeter of 2d shapes": "perimeterShapes",
  "volume of a cuboid": "volumeCuboid",
  "coordinates": "coordinates",
  "more coordinates": "coordinates",
  "four quadrants": "coordinates",
  "coordinate pairs": "coordinates",
  "shapes on a coordinate grid": "coordinates",
  "translations": "coordinates",
  "translation": "coordinates",
  "translations on a coordinate grid": "coordinates",
  "reflection and translation": "coordinates",
  "reflections on a grid": "coordinates",
  "coordinates and translation of 2d shapes": "coordinates",
  "angles": "angleTypes",
  "angles and turns": "angleTypes",
  "identifying and reasoning about angles": "angleTypes",
  "measuring and drawing angles": "angleTypes",
  "block graphs": "readTable",
  "pictograms and block graphs": "readTable",
  "pictograms and bar charts": "readTable",
  "bar charts and dot plots": "readTable",
  "tally charts": "readTable",
  "frequency charts": "readTable",
  "tables lists and pictograms": "readTable",
  "pictograms lists and tables": "readTable",
  "lists tables charts and graphs": "readTable",
  "collecting and sorting data": "readTable",
  "collecting and comparing information": "readTable",
  "interpreting and comparing data": "readTable",
  "comparing data and charts": "readTable",
  "chance": "chanceLanguage",
  "certain impossible likely unlikely": "chanceLanguage",
  "equally likely more likely less likely": "chanceLanguage",
  "probability experiments": "simpleProbability",
  "probability and likelihood of events": "simpleProbability",
  "probability and proportionality": "simpleProbability",
  "probability": "simpleProbability",
  "mode and median": "modeMedianRange",
  "averages and the range": "modeMedianRange",
  "averages": "modeMedianRange",
  "substitution into expressions and formulae": "substitution",
  "deriving and using a formula": "substitution",
  "using letters to represent quantities": "substitution",
  "algebraic expressions and formulae": "substitution",
  "simplifying algebraic expressions": "simplifyExpressions",
  "expressions": "simplifyExpressions",
  "simplifying calculations": "simplifyExpressions",
  "angles around a point": "angleFacts",
  "angles formed within parallel lines": "angleFacts",
  "angle properties": "angleFacts",
  "angle properties of quadrilaterals": "angleFacts",
  "angle relationships and polygons": "polygonAngles",
  "percentage change": "percentChange",
  "compound percentages": "percentChange",
  "compound interest": "percentChange",
  "further percentages": "percentChange",
  "speed distance and time": "speedDistanceTime",
  "travel graphs": "speedDistanceTime",
  "travel graphs and compound measures": "speedDistanceTime",
  "motion graphs": "speedDistanceTime",
  "volume of a prism": "prismVolume",
  "surface area of a prism": "prismVolume",
  "upper and lower bounds": "bounds",
  "calculating with upper and lower bounds": "bounds",
  "accuracy": "bounds",
  "surds": "surds",
  "rationalising denominators": "surds",
  "rational and irrational numbers": "surds",
  "the nth term of an arithmetic sequence": "arithmeticSeries",
  "the sum of the first n terms of an arithmetic series": "arithmeticSeries",
  "the nth term of a geometric sequence": "geometricSeries",
  "the sum of a finite geometric series": "geometricSeries",
  "the sum to infinity of a convergent geometric series": "geometricSeries",
  "functions": "compositeFunctions",
  "functions inverse functions and composite functions": "compositeFunctions",
  "function machines": "compositeFunctions",
  "circular measure": "circularMeasure",
  "arc length": "circularMeasure",
  "areas of sectors and segments": "circularMeasure",
  "radian measure": "circularMeasure",
  "the sine rule": "sineCosineRule",
  "the cosine rule": "sineCosineRule",
  "area of triangles": "sineCosineRule",
  "the area of a triangle": "sineCosineRule",
  "further trigonometry": "sineCosineRule",
  "vectors": "vectors2D",
  "position vectors": "vectors2D",
  "magnitude of a vector": "vectors2D",
  "the magnitude of a vector": "vectors2D",
  "addition and subtraction of vectors": "vectors2D",
  "translation vectors": "vectors2D",
  "vectors definition and vector geometry": "vectors2D",
  "completing the square": "completeSquare",
  "the discriminant": "completeSquare",
  "polynomials": "polynomialTheorems",
  "dividing a polynomial by a linear expression": "polynomialTheorems",
  "algebra the modulus function": "modulusFunction",
  "the normal distribution": "normalDistribution",
  "using the normal distribution": "normalDistribution",
  "non standardised variables": "normalDistribution",
  "probability distributions": "discreteRandomVariable",
  "probability distribution of discrete random variables": "discreteRandomVariable",
  "expectation of x": "discreteRandomVariable",
  "variance of x": "discreteRandomVariable",
  "the product rule": "productQuotientRule",
  "the quotient rule": "productQuotientRule",
  "using the and symbols": "addWithin20",
  "using mental strategies to add and subtract": "columnAdd",
  "adding in a different order": "multiplesOf10",
  "dividing 2 digit numbers": "divisionRemainder",
  "area": "areaPerimeterRect",
  "reflecting shapes": "coordinates",
  "position and direction": "compassDirections",
  "position and movement": "compassDirections",
  "direction and movement": "compassDirections",
  "position direction and movement": "compassDirections",
  "north south east west": "compassDirections",
  "directions and maps": "compassDirections",
  // Senior wording
  "logarithmic and exponential functions": "logarithms",
  "logarithms in other bases": "logarithms",
  "the laws of logarithms": "logarithms",
  "the relationship between exponents and logarithms": "logarithms",
  "using logarithms to solve equations and inequalities": "logarithms",
  "solving equations of the form a b": "expEquations",
  "indices standard form and surds": "standardForm",
  "algebraic indices": "indices",
  "index laws": "indices",
  "negative and fractional indices": "indices",
  "algebraic representation and manipulation": "factorise",
  "expanding the product of two algebraic expressions": "expandBrackets",
  "measures of variation": "standardDeviation",
  "variance and standard deviation": "standardDeviation",
  "mean median mode and range": "meanOfNumbers",
  "mode mean median range": "meanOfNumbers",
  "series": "binomial",
  "using the binomial expansion to expand brackets": "binomial"
};

// Best-matching generator for a curriculum topic name, or null.
//
// Every significant word of the shorter of the two names must be matched.
// A partial overlap is not good enough: "The binomial and geometric
// distributions" shares "binomial" with the binomial *expansion* generator
// but is a different topic entirely, and a wrong lesson is worse than none.
// A tie between two generators is also treated as no match.
function matchGenerator(name) {
  const alias = TOPIC_ALIASES[String(name).toLowerCase().replace(/[^a-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim()];
  if (alias && GENERATORS[alias]) return alias;

  const want = new Set(words(name));
  if (!want.size) return null;
  const hits = [];
  Object.keys(GENERATORS).forEach((id) => {
    const have = new Set(words(GENERATORS[id].name));
    const shared = [...want].filter((w) => have.has(w));
    if (shared.length < Math.min(want.size, have.size)) return;
    if (!shared.some((w) => w.length >= 5)) return;   // "time" or "area" alone is not enough
    hits.push(id);
  });
  return hits.length === 1 ? hits[0] : null;
}

// Every track a grade offers, in the order data.js lists them.
function tracksForGrade(grade) {
  const g = CURRICULUM.find((x) => x.id === grade) || CURRICULUM[0];
  return g.tracks;
}

// Flat list of every sub-topic in one grade and stream, each with the generator
// that covers it (or null). The key is unique per topic: two sub-topics can
// legitimately map to the same generator, and keying by generator merges them.
function topicRegistry(grade, trackIndex) {
  const tracks = tracksForGrade(grade);
  const track = tracks[Math.min(trackIndex || 0, tracks.length - 1)];
  const out = [];
  track.strands.forEach((strand) => {
    strand.topics.forEach((t) => {
      out.push({
        key: `${track.key}|${t.n}`,
        name: t.n,
        strand: strand.name,
        month: t.m || "",
        detail: t.s || "",
        note: t.t || "",
        gen: matchGenerator(t.n)
      });
    });
  });
  return out;
}
